<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="igate-pc" failures="1" tests="4" name="Test(failed)" time="4.151" errors="0" timestamp="2024-04-25T16:30:13 IST">
  <testcase classname="testcases.TC_02_Login" name="login" time="0.619">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testcases.TC_02_Login.login(TC_02_Login.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testcases.TC_02_Login" name="login_data_entry" time="0.0">
    <skipped/>
  </testcase> <!-- login_data_entry -->
  <testcase classname="testcases.TC_02_Login" name="loggingout" time="0.0">
    <skipped/>
  </testcase> <!-- loggingout -->
  <testcase classname="testcases.TC_02_Login" name="logoutToHome" time="0.001">
    <skipped/>
  </testcase> <!-- logoutToHome -->
</testsuite> <!-- Test(failed) -->
